### ISSUE TITLE
can the weights from the original repo be load in this repo?

### ISSUE THREAD

**Issue by Edwardmark** [Okery/YOLOv5-PyTorch#4]
How to test use the model trained from the original yolo-v5 repo in your repo?
I mean how to load the model. Thanks.

**Comment by Okery** [comment]
Actually, it is not an easy thing to load the original weight. Although this repo's model performs as same as the original one (version 2.0), they are different in the order of layers. You have to be very familiar with their structure before changing the order of weights' values.

I will modify the original weights to make them work for this repo later, i.e., adding YOLOv5m, YOLOv5l and YOLOv5x weights.

**Comment by CharlesAntoineParent** [comment]
Hello, did you add the other weights or not yet ?
